site_name: Human Interface Guidelines
# Temporary location, using GitHub Pages.
site_url: https://julianeisel.github.io/Blender-HIG/
copyright: >
  &copy; Copyright: This page is licensed under a CC-BY-SA 4.0 Int. License.

theme:
  name: material
  # Theme extensions.
  custom_dir: overrides
  logo: assets/blender_logo.png
  favicon: assets/blender_favicon.png
  language: en
  palette:
    scheme: blender_light
    accent: blue
  features:
    # Don't reload the entire site when changing pages. (Material for MkDocs
    # only.) -- Doesn't work with Disqus it seems.
    # - navigation.instant
    # Main horizontal navigation tabs.
    - navigation.tabs
    - navigation.top

# Custom variables.
extra:
  info:
    license_str: "CC-BY-SA 4.0 Int."
  disqus: blender-hig

extra_css:
  # Our own theme settings.
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

markdown_extensions:
  # "Call-outs": Boxes for notes, warnings, summaries, etc.
  - admonition
  # Abbreviations.
  - abbr
  # Custom attributs for headers, e.g. achors (`# Foo Bar { #foo-bar }`).
  # Together with def_list also works for definitions.
  - attr_list
  # Definition lists.
  - def_list
  - footnotes
  # Code blocks with highlighting.
  - pymdownx.highlight
  # Collapsible "call-outs".
  - pymdownx.details
  # Shortcut displaying (e.g ++shift+enter++)
  - pymdownx.keys
  # Tabbed boxes
  - pymdownx.tabbed
  # Nesting of code and content blocks inside "call-outs".
  - pymdownx.superfences
  # Allows "including" contents from other files (e.g. for common
  # abbreviations).
  - pymdownx.snippets
  # Metadata extension to support "front matter", i.e. setting properties per
  # site (like hiding ToC).
  - meta
  # Checkbox lists.
  - pymdownx.tasklist:
      custom_checkbox: false
  - toc:
      # Permanent section links ("anchors"). Appear on hover.
      permalink: ⚓︎

plugins:
  - macros

# Main site navigation tree.
nav:
  - Home: index.md
  - Guidelines:
    - Design Philosophy:
      - Why it Matters: design-philosophy/why-it-matters.md
      - design-philosophy/values.md
      - design-philosophy/paradigms.md
    - Process:
      - process/index.md
      - process/user-centered-design.md
    - Architecture:
      - architecture/hierarchy.md
      - architecture/layouts.md
    - User Communication:
      - user-communication/writing-style.md
      - user-communication/dialogs.md
    - Components:
      - components/sidebar-tabs.md
    - Visual Design:
      - visual-design/icons.md
      - visual-design/dark-theme.md
      - visual-design/light-theme.md
    - glossary.md
  - About:
    - about/contribute.md
    - about/license.md
